version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: like-windows-explore-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db-like-windows-explore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
